### ISSUE TITLE
Auto login breaks when accessing APIs when token expires

### ISSUE THREAD

**Issue by ml5174** [ml5174/sacpcp#65]
To fix we should check for a valid token on load if one exists and if it fails remove token.

**Comment by ml5174** [comment]
A possible solution is to have a common error handler function in user.ts.  If the error is related to the expired token then you can call the user.logout() function.

**Comment by pp4253** [comment]
How to recreate the issue?

**Comment by ml5174** [comment]
Recreating the issue is difficult,  what could be done is that the key that is stored in "Local Storage" would need to change to a different invalid value.  This will simulate the issue.

**Comment by pp4253** [comment]
Added extra steps to prevent break in Auto Login after Token expiration

**Comment by pp4253** [comment]
Please review
